apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1-s3-artifact-repository
data:
  default-v1-s3-artifact-repository: |
    s3:
      endpoint: minio-service:9000
      bucket: argo-bucket
      accessKeySecret:
        key: accesskey
        name: argo-artifacts
      secretKeySecret:
        key: secretkey
        name: argo-artifacts
      insecure: true
