# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8090:3306
    networks:
      - statsd
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: application
      MYSQL_PASSWORD: passpass

  adminer:
    image: adminer
    restart: always
    networks:
      - statsd
    ports:
      - 8085:8080

networks:
  statsd:
    external: true